[reporting]
disable = [
  "W101",
  "W102",
  "W103",
  "W104",
  "W105",
  "W106",
  "C101",
  "C102",
  "C103",
  "R101",
  "R201",
  "R202",
  "W301",
  "C301",
  "C302",
  "R301",
  "C401",
  "C402",
]
