[reporting]
disable = [
  "E001"            # File could not be parsed: {error_msg}
  "E101"            # ‘{parameter}’ is not defined in the Examples section
  "R101"            # Parameter ‘{parameter}’ is not used
]
 
