name: Gherkin Lint

on:
  pull_request:
    paths:
      - "features/**/*.feature"
      - "gherlint.toml"
      - ".github/workflows/gherlint.yml"
  push:
    paths:
      - "features/**/*.feature"
      - "gherlint.toml"
      - ".github/workflows/gherlint.yml"

jobs:
  gherlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python -m pip install --upgrade pip
      - run: python -m pip install gherlint==0.5.0
      - run: gherlint lint features
